### ISSUE TITLE
Corrupted PDF file

### ISSUE THREAD

**Issue by ycopin** [dcmvdbekerom/pypdfplot#15] opened 2020-11-20 18:05 UTC
I tried with the following code:
```
import numpy as N
import pypdfplot as P

yy, xx = N.mgrid[-1:+1:100j, -1:+1:100j]   # Coordinate images
t = N.full((100, 100), 0.9)                # Mean transmission map
v = N.r_[[1]*75,1:0.9:25j].reshape(-1, 1)  # Vignetting profile

P.imshow(t * v, vmin=0.81, vmax=0.9, cmap='bone')
P.colorbar()

P.publish()
```
which generated the attached PDF.
[rgs270_vignetting.pdf](https://github.com/dcmvdbekerom/pypdfplot/files/5574755/rgs270_vignetting.pdf)
However, when opened with evince (GNOME Document Viewer 3.18.2), it displays something like
![Screenshot from 2020-11-20 17-09-42](https://user-images.githubusercontent.com/812050/99823460-b773d100-2b54-11eb-83a6-00375be89919.png)
while it should look as
![rgs270_vignetting](https://user-images.githubusercontent.com/812050/99824429-ffdfbe80-2b55-11eb-82b7-aeb37ccadd81.png)

Did I do anything wrong?

**Comment by ycopin** [comment] 2020-11-20 18:08
I should add that ImageMagic (6.8.9-9 Q16 x86_64 2019-11-12) `convert` is not happy with the PDF:
```
$ convert rgs270_vignetting.pdf tmp.png
   **** Warning: File has some garbage before %PDF- .
   **** Error reading a content stream. The page may be incomplete.
               Output may be incorrect.
   **** Error: File did not complete the page properly and may be damaged.
               Output may be incorrect.
```

**Comment by dcmvdbekerom** [comment] 2020-11-21 07:32
I am getting a similar error so this is a bug in ``pypdfplot``, not in your script. My guess is the issue is in ``PyPDF4`` but I need to look into this a little more. 

To your second comment: The " **** Warning: File has some garbage before %PDF- ." is because The PDF header (which is ``%PDF``) is preceded by ``#`` to make it appear as comment in Python. This is allowed according to the PDF specification but some readers can be bit more strict and demand ``%PDF`` is the first thing they see. I don't see any way around this as the pypdfplot document must be interpretable by both Python and PDF readers.

The two errors are probably related to the reason the figure is not showing properly, which I will look into. Thank you for reporting!

**Comment by dcmvdbekerom** [comment] 2020-11-22 06:35
The bug was in how ``pypdfplot`` applies the ASCIIHexEncode. Filters may have parameters controlled by /DecodeParms. If there are multiple filters  with some having non-default values, they should have be added as an array. This is now fixed!

Fixed in https://github.com/dcmvdbekerom/pypdfplot/commit/54c465e1a7c8af58f9645a0251367fa756bfff0c (development branch) will merge soon.

**Closed as completed by dcmvdbekerom** 2020-11-22 06:35 UTC
Labels: bug

**Comment by dcmvdbekerom** [comment] 2020-11-22 06:54
By the way, please let me know if this fixed your issue.
Specifically, I'd be curious if ImageMagic now handles the files better.

**Comment by ycopin** [comment] 2020-11-23 16:17
Great, the bug is fixed: the generated PDF displays properly in evince, and is handled nicely by ImageMagick only with an inconsequential warning (`**** Warning: File has some garbage before %PDF- .`) Thanks for the quick feedback and fix!
